#define DRIVE_TYPE DRIVE_TANK
#define DRIVE_TANK_LEFT MOTOR_OUT(1) MOTOR_OUT(6)
#define DRIVE_TANK_RIGHT MOTOR_OUT(11) MOTOR_OUT(12)
#define DRIVE_TANK_INPUT_TYPE DRIVE_TANK_INPUT_COMPLEX
DRIVE_TANK_INPUT_COMPLEX_SPEED_JOYSTICK(A)
DRIVE_TANK_INPUT_COMPLEX_DIRECTION_JOYSTICK(C)
CONDITIONAL(BUTTON(RUp), SET_MOTOR(2, 127))
CONDITIONAL(BUTTON(RDown), SET_MOTOR(2, -127))
CONDITIONAL(!(BUTTON(RUp) || BUTTON(RDown)), SET_MOTOR(2, 0))
