#define DRIVE_TYPE DRIVE_TANK
#define DRIVE_TANK_INPUT_TYPE DRIVE_TANK_INPUT_COMPLEX
DRIVE_TANK_INPUT_COMPLEX_SPEED_JOYSTICK(A)
DRIVE_TANK_INPUT_COMPLEX_DIRECTION_JOYSTICK(C)
#define DRIVE_TANK_LEFT MOTOR_OUT(7) MOTOR_OUT(5)
#define DRIVE_TANK_RIGHT MOTOR_OUT(12) MOTOR_OUT(3)
TOUCH_LED_DIRECTION_BASED(8)
TOUCH_LED_DIRECTION_BASED(9)
