// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#pragma config(Sensor, port7,  touch_led,      sensorVexIQ_LED)
#pragma config(Motor,  motor1,          left_drive,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          right_drive,   tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int l, r;

#define COLOR_COUNT 9
int color[COLOR_COUNT] = { colorRed, colorOrange, colorYellow, colorLimeGreen, colorGreen, colorBlueGreen, colorBlue, colorViolet, colorRedViolet };
int color_index = 0;
bool lastTouch = false;

task main()
{
	while (true) {
	motor[left_drive] = l = vexRT[ChA];
	motor[right_drive] = r = vexRT[ChD];
	bool touch = SensorValue[touch_led] != 0;
	if (touch && !lastTouch)
		setTouchLEDColor(touch_led, color[color_index++ % COLOR_COUNT]);
	lastTouch = touch;
	sleep(10);
	}
}
