#pragma config(Sensor, port7,  touch_led,      sensorVexIQ_LED)
#pragma config(Motor,  motor1,          left_drive,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          right_drive,   tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int l, r;

#define COLOR_COUNT 9
int color[COLOR_COUNT] = { colorRed, colorOrange, colorYellow, colorLimeGreen, colorGreen, colorBlueGreen, colorBlue, colorViolet, colorRedViolet };
int color_index = 0;
bool lastTouch = false;

task main()
{
	while (true) {
	motor[left_drive] = l = vexRT[ChA];
	motor[right_drive] = r = vexRT[ChD];
	bool touch = SensorValue[touch_led] != 0;
	if (touch && !lastTouch)
		setTouchLEDColor(touch_led, color[color_index++ % COLOR_COUNT]);
	lastTouch = touch;
	sleep(10);
	}
}
